#!/usr/bin/python

import time
import requests
import json
import sys
import urllib2
import time
from datetime import datetime, timedelta


count=0



while 1 :
    t = time.localtime()
    tsec = t.tm_sec
    if tsec%10!=0 :
            print tsec
            time.sleep(1)
    else :

        count=count+1
        url = "http://127.0.0.1:4242/api/put"

        data = {
                 "metric": "foo.bar",
                 "timestamp": time.time(),
                 "value": count,
                 "tags": {
                         "host": "mypc"
                 }
        }

        ret = requests.post(url, data=json.dumps(data))
        print "ok"
        time.sleep(1)






끝!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
